### PR TITLE
Convert NaN to correct type in sqrt

### PR DESCRIPTION
**Pull request by DanielVandH**

### CODE REVIEW

**Comment by DanielVandH** [comment]
Ah, I'm guessing the integer issues are a reason for not converting it initially? Unless perhaps 

`sqrt(x::T) where {T<:Number}`

and 

`sqrt(x::Integer)`

ought to be separated? The point being for floats to at least be able to avoid e.g.

```julia
julia> @code_warntype NaNMath.sqrt(-0.3)
MethodInstance for NaNMath.sqrt(::Float64)
  from sqrt(x::Real) in NaNMath at C:\Users\licer\.julia\packages\NaNMath\MNJRI\src\NaNMath.jl:21
Arguments
  #self#::Core.Const(NaNMath.sqrt)
  x::Float64
Body::Float64
1 ─ %1 = (x < 0.0)::Bool
└──      goto #3 if not %1
2 ─      return NaNMath.NaN
t(::Float32)
  from sqrt(x::Real) in NaNMath at C:\Users\licer\.julia\packages\NaNMath\MNJRI\src\NaNMath.jl:21
Arguments
  #self#::Core.Const(NaNMath.sqrt)
  x::Float32
Body::Union{Float32, Float64}
1 ─ %1 = (x < 0.0)::Bool
└──      goto #3 if not %1
2 ─      return NaNMath.NaN
3 ─ %4 = Base.getproperty(NaNMath.Base, :sqrt)::Core.Const(sqrt)
│   %5 = (%4)(x)::Float32
└──      return %5
```

**Comment by mlubin** [comment]
For which types `T` is `T(NaN)` supposed to work? I'd guess `T <: AbstractFloat` is ok, but we'd need to check to be sure.

**Comment by DanielVandH** [comment]
I believe only `AbstractFloat`s, based on this definition of `isnan` from Base

```julia
isnan(x::AbstractFloat) = (x != x)::Bool
isnan(x::Number) = false
```

checking only `AbstractFloat`s.

**Comment by mlubin** [comment]
```julia
sqrt(x::T) where {T<:AbstractFloat} = x < 0.0 ? T(NaN) : Base.sqrt(x)
sqrt(x::Real) = sqrt(float(x))
```
seems reasonable then

**Pull request merged**
